server:
 port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
 cloud:
  config:
      enabled: false
 application:
  name: PGMR-SERVICE
 
